export const TEMPLATES = [
    {
      id: "landing-page-01",
      title: "Landing Page Moderna",
      name: "Landing Page Moderna",
      category: "Landing Page",
      image: "/templates/landing-page-01.png",
      tags: ["Next.js 15", "React 19", "TypeScript", "Tailwind CSS 4", "Framer Motion", "Radix UI", "Responsivo", "Dark Mode"],
      installCommand: "npx create-template-vncsraniery@latest add landing-01",
      description: "Template completo de Landing Page moderna com design elegante, animações fluidas e total responsividade para projetos web profissionais.",
      longDescription: "Este template representa o estado da arte em desenvolvimento de Landing Pages modernas, combinando as mais recentes tecnologias web com design excepcional e performance otimizada. Desenvolvido com Next.js 15 e React 19, oferece uma base sólida para projetos web profissionais que precisam impressionar desde o primeiro contato visual.\n\nO design minimalista e elegante é complementado por animações fluidas e efeitos visuais interativos que criam uma experiência de usuário envolvente e memorável. O sistema de temas completo permite alternância suave entre modo claro e escuro, adaptando-se às preferências do usuário e mantendo a consistência visual em todas as interações.\n\nA arquitetura responsiva mobile-first garante uma experiência perfeita em todos os dispositivos, desde smartphones até desktops de alta resolução. Os componentes interativos únicos, como Magic Cards com efeitos de gradiente que seguem o mouse e Magic Badges com animações de rotação, adicionam um toque de sofisticação e modernidade.\n\nA navegação inteligente com detecção de scroll e menu mobile animado proporciona uma experiência de navegação intuitiva e fluida. A estrutura de código bem organizada e escalável, combinada com TypeScript para tipagem forte, facilita a manutenção e expansão do projeto.\n\nAs otimizações de performance incluem lazy loading de componentes, bundle splitting inteligente e otimizações automáticas de imagem, garantindo tempos de carregamento rápidos e uma experiência de usuário excepcional. Este template é ideal para desenvolvedores que buscam criar Landing Pages de alta qualidade com funcionalidades avançadas e design profissional.",
      features: [
        "Design moderno com animações fluidas e efeitos visuais interativos",
        "Sistema completo de temas dark/light com transições suaves",
        "Totalmente responsivo com mobile-first approach",
        "Componentes interativos (Magic Cards, Magic Badges animados)",
        "Navegação responsiva com scroll detection e menu mobile",
        "Next.js 15 com Turbopack e React 19",
        "TypeScript com tipagem forte",
        "Tailwind CSS 4 com animações customizadas",
        "Radix UI para componentes acessíveis",
        "Performance otimizada com lazy loading",
        "Acessibilidade seguindo melhores práticas",
        "Estrutura bem organizada e escalável",
      ],
      demoUrl: "#",
      codeUrl: "https://github.com/VncsRaniery/quickstart-ui-templates/tree/main/templates/landing-01",
      featured: true,
      price: "Gratuito",
      difficulty: "Intermediário",
      lastUpdated: "2025-09-20",
    },
  ]